###
POST http://localhost:8081/demo/add
Content-Type: application/json

{
    "username": "生一鸣",
    "address": "江苏省无锡市惠山区",
    "age": 28
}

###
GET http://localhost:8081/demo/get/c9cb8f8a-d0fc-4479-8f15-7d3b945122cf

###
POST http://localhost:8081/demo/query
Content-Type: application/json

{
    "address": "无锡"
}