###
POST http://localhost:8081/demo/add
Content-Type: application/json

{
    "username": "生一鸣",
    "address": "江苏省无锡市惠山区",
    "age": 28
}

###
GET http://localhost:8081/demo/get/cde2fe11-2329-4c50-b689-88bafc1f2f13
